const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config();
const Character = require("../api/models/characters.model");

const MONGODB_URL = process.env.MONGODB_URL;

const characters = [
    {
      nombre: "Blancanieves",
      rol: "Protagonista",
      aliados: ["Doc", "Feliz", "Gruñón", "Tímido", "Sabio", "Mudito", "Dengoso", "Príncipe"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Canto", "Baile", "Comunicación con animales"],
    },
    {
      nombre: "Reina Malvada",
      rol: "Villano",
      aliados: [],
      enemigos: ["Blancanieves", "Príncipe"],
      descripcion: ["Magia oscura", "Transformación"],
    },
    {
      nombre: "Doc",
      rol: "Aliado",
      aliados: ["Blancanieves", "Gruñón", "Feliz", "Tímido", "Sabio", "Mudito", "Dengoso", "Príncipe"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Consejos sabios", "Cuidado de plantas"],
    },
    {
      nombre: "Feliz",
      rol: "Aliado",
      aliados: ["Blancanieves", "Doc", "Gruñón", "Tímido", "Sabio", "Mudito", "Dengoso", "Príncipe"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Alegría contagiosa", "Buen sentido del humor"],
    },
    {
      nombre: "Gruñón",
      rol: "Aliado",
      aliados: ["Blancanieves", "Doc", "Feliz", "Tímido", "Sabio", "Mudito", "Dengoso", "Príncipe"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Expresiones gruñonas", "Trabajo duro"],
    },
    {
      nombre: "Tímido",
      rol: "Aliado",
      aliados: ["Blancanieves", "Doc", "Feliz", "Gruñón", "Sabio", "Mudito", "Dengoso", "Príncipe"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Timidez adorable", "descripcion para esconderse"],
    },
    {
      nombre: "Sabio",
      rol: "Aliado",
      aliados: ["Blancanieves", "Doc", "Feliz", "Gruñón", "Tímido", "Mudito", "Dengoso", "Príncipe"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Sabiduría profunda", "Lectura de libros"],
    },
    {
      nombre: "Mudito",
      rol: "Aliado",
      aliados: ["Blancanieves", "Doc", "Feliz", "Gruñón", "Tímido", "Sabio", "Dengoso", "Príncipe"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Silencio elocuente", "Lenguaje de señas"],
    },
    {
      nombre: "Dengoso",
      rol: "Aliado",
      aliados: ["Blancanieves", "Doc", "Feliz", "Gruñón", "Tímido", "Sabio", "Mudito", "Príncipe"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Llanto conmovedor", "Reacciones dramáticas"],
    },
    {
      nombre: "Príncipe Florian",
      rol: "Aliado",
      aliados: ["Blancanieves"],
      enemigos: ["Reina Malvada"],
      descripcion: ["Valentía", "Espada"],
    },
    {
        nombre: "Cenicienta",
        rol: "Protagonista",
        aliados: ["Hada Madrina", "Animales del bosque"],
        enemigos: ["Madrastra", "Hermanastras"],
        descripcion: ["Bondad", "Canto", "Baile"],
      },
      {
        nombre: "Hada Madrina",
        rol: "Aliado",
        aliados: ["Cenicienta", "Animales del bosque"],
        enemigos: ["Madrastra", "Hermanastras"],
        descripcion: ["Magia", "Transformación"],
      },
      {
        nombre: "Madrastra",
        rol: "Villano",
        aliados: ["Anastasia", "Drizella"],
        enemigos: ["Cenicienta", "Hada Madrina"],
        descripcion: ["Manipulación", "Crueldad"],
      },
      {
        nombre: "Anastasia",
        rol: "Villano",
        aliados: ["Madrastra", "Drizella"],
        enemigos: ["Cenicienta", "Hada Madrina"],
        descripcion: ["Envidia", "Maltrato"],
      },
      {
        nombre: "Drizella",
        rol: "Villano",
        aliados: ["Madrastra", "Anastasia"],
        enemigos: ["Cenicienta", "Hada Madrina"],
        descripcion: ["Envidia", "Maltrato"],
      },
      {
        nombre: "Príncipe Encantador",
        rol: "Aliado",
        aliados: ["Cenicienta"],
        enemigos: [],
        descripcion: ["Valentía", "Búsqueda del amor verdadero"],
      },
      {
        nombre: "Ratoncitos",
        rol: "Aliado",
        aliados: ["Cenicienta", "Hada Madrina"],
        enemigos: [],
        descripcion: ["Ayuda doméstica", "Trabajo en equipo"],
      },
      {
        nombre: "Bella",
        rol: "Protagonista",
        aliados: ["Bestia", "Lumière", "Ding Dong", "Cogsworth", "Mrs. Potts", "Chip", "Maurice"],
        enemigos: ["Gastón", "LeFou"],
        descripcion: ["Inteligencia", "Amor por la lectura"],
      },
      {
        nombre: "Bestia",
        rol: "Protagonista",
        aliados: ["Bella", "Lumière", "Mrs. Potts", "Cogsworth", "Chip", "Maurice"],
        enemigos: ["Gastón", "LeFou"],
        descripcion: ["Fuerza", "Transformación"],
      },
      {
        nombre: "Lumière",
        rol: "Aliado",
        aliados: ["Bella", "Bestia", "Cogsworth", "Mrs. Potts", "Chip", "Maurice"],
        enemigos: ["Gastón", "LeFou"],
        descripcion: ["Candelabro mágico", "Entretenimiento"],
      },
      {
        nombre: "Cogsworth",
        rol: "Aliado",
        aliados: ["Bella", "Bestia", "Lumière", "Mrs. Potts", "Chip", "Maurice"],
        enemigos: ["Gastón", "LeFou"],
        descripcion: ["Reloj mágico", "Organización"],
      },
      {
        nombre: "Mrs. Potts",
        rol: "Aliado",
        aliados: ["Bella", "Bestia", "Lumière", "Cogsworth", "Chip", "Maurice"],
        enemigos: ["Gastón", "LeFou"],
        descripcion: ["Tetera mágica", "Maternal"],
      },
      {
        nombre: "Chip",
        rol: "Aliado",
        aliados: ["Bella", "Bestia", "Lumière", "Cogsworth", "Mrs. Potts", "Maurice"],
        enemigos: ["Gastón", "LeFou"],
        descripcion: ["Taza encantada", "Inocencia"],
      },
      {
        nombre: "Maurice",
        rol: "Aliado",
        aliados: ["Bella", "Bestia", "Lumière", "Cogsworth", "Mrs. Potts", "Chip"],
        enemigos: ["Gastón", "LeFou"],
        descripcion: ["Inventor", "Amor por su hija"],
      },
      {
        nombre: "Gastón",
        rol: "Villano",
        aliados: ["LeFou"],
        enemigos: ["Bella", "Bestia", "Lumière", "Cogsworth", "Mrs. Potts", "Chip", "Maurice"],
        descripcion: ["Fuerza física", "Vanidad"],
      },
      {
        nombre: "LeFou",
        rol: "Villano",
        aliados: ["Gastón"],
        enemigos: ["Bella", "Bestia", "Lumière", "Cogsworth", "Mrs. Potts", "Chip", "Maurice"],
        descripcion: ["Seguidor leal", "Cómico"],
      },
      {
        nombre: "Simba",
        rol: "Protagonista",
        aliados: ["Nala", "Mufasa", "Timón", "Pumbaa", "Rafiki"],
        enemigos: ["Scar", "Hienas"],
        descripcion: ["Rugido", "Agilidad"],
      },
      {
        nombre: "Nala",
        rol: "Protagonista",
        aliados: ["Simba", "Mufasa", "Timón", "Pumbaa", "Rafiki"],
        enemigos: ["Scar", "Hienas"],
        descripcion: ["Caza", "Inteligencia"],
      },
      {
        nombre: "Mufasa",
        rol: "Aliado",
        aliados: ["Simba", "Nala", "Rafiki", "Zazu"],
        enemigos: ["Scar", "Hienas"],
        descripcion: ["Rey sabio", "Fuerza"],
      },
      {
        nombre: "Scar",
        rol: "Villano",
        aliados: ["Hienas"],
        enemigos: ["Simba", "Mufasa", "Nala", "Timón", "Pumbaa", "Rafiki"],
        descripcion: ["Astucia", "Manipulación"],
      },
      {
        nombre: "Timón",
        rol: "Aliado",
        aliados: ["Simba", "Nala", "Pumbaa", "Rafiki"],
        enemigos: ["Scar", "Hienas"],
        descripcion: ["Hakuna Matata", "Astucia"],
      },
      {
        nombre: "Pumbaa",
        rol: "Aliado",
        aliados: ["Simba", "Nala", "Timón", "Rafiki"],
        enemigos: ["Scar", "Hienas"],
        descripcion: ["Hakuna Matata", "Fuerza"],
      },
      {
        nombre: "Rafiki",
        rol: "Aliado",
        aliados: ["Simba", "Nala", "Mufasa", "Timón", "Pumbaa"],
        enemigos: ["Scar", "Hienas"],
        descripcion: ["Sabiduría", "Conexión espiritual"],
      },
      {
        nombre: "Zazu",
        rol: "Aliado",
        aliados: ["Mufasa"],
        enemigos: ["Scar", "Hienas"],
        descripcion: ["Consejero real", "Lealtad"],
      },
      {
        nombre: "Hienas",
        rol: "Villano",
        aliados: ["Scar"],
        enemigos: ["Simba", "Mufasa", "Nala", "Timón", "Pumbaa", "Rafiki"],
        descripcion: ["Seguidoras leales", "Astucia"],
      },
      {
        nombre: "Pinocho",
        rol: "Protagonista",
        aliados: ["Pepito Grillo", "Hada Azul", "Gepetto", "Jiminy Cricket"],
        enemigos: ["El Zorro", "Gato", "Stromboli", "Monstruo Ballena"],
        descripcion: ["Nariz creciente", "Innocencia"],
      },
      {
        nombre: "Pepito Grillo",
        rol: "Aliado",
        aliados: ["Pinocho", "Hada Azul", "Gepetto"],
        enemigos: ["El Zorro", "Gato", "Stromboli", "Monstruo Ballena"],
        descripcion: ["Consejero", "Conciencia"],
      },
      {
        nombre: "Hada Azul",
        rol: "Aliado",
        aliados: ["Pinocho", "Pepito Grillo", "Gepetto"],
        enemigos: ["El Zorro", "Gato", "Stromboli", "Monstruo Ballena"],
        descripcion: ["Magia", "Concesión de deseos"],
      },
      {
        nombre: "Gepetto",
        rol: "Aliado",
        aliados: ["Pinocho", "Pepito Grillo", "Hada Azul"],
        enemigos: ["El Zorro", "Gato", "Stromboli", "Monstruo Ballena"],
        descripcion: ["Carpintería", "Amor paternal"],
      },
      {
        nombre: "El Zorro",
        rol: "Villano",
        aliados: ["Gato"],
        enemigos: ["Pinocho", "Pepito Grillo", "Hada Azul", "Gepetto"],
        descripcion: ["Estafador", "Tramposo"],
      },
      {
        nombre: "Gato",
        rol: "Villano",
        aliados: ["El Zorro"],
        enemigos: ["Pinocho", "Pepito Grillo", "Hada Azul", "Gepetto"],
        descripcion: ["Estafador", "Tramposo"],
      },
      {
        nombre: "Stromboli",
        rol: "Villano",
        aliados: [],
        enemigos: ["Pinocho", "Pepito Grillo", "Hada Azul", "Gepetto"],
        descripcion: ["Titiritero malvado", "Ambición"],
      },
      {
        nombre: "Monstruo Ballena",
        rol: "Villano",
        aliados: [],
        enemigos: ["Pinocho", "Pepito Grillo", "Hada Azul", "Gepetto"],
        descripcion: ["Apariencias engañosas", "Peligro acuático"],
      },
      {
        nombre: "Dumbo",
        rol: "Protagonista",
        aliados: ["Timoteo", "La Cigüeña", "Sr. Ratón", "Sra. Jumbo"],
        enemigos: ["Elefantes crueles"],
        descripcion: ["Vuelo", "Orejas grandes"],
      },
      {
        nombre: "Timoteo",
        rol: "Aliado",
        aliados: ["Dumbo", "La Cigüeña", "Sr. Ratón", "Sra. Jumbo"],
        enemigos: ["Elefantes crueles"],
        descripcion: ["Amigo leal", "Astucia"],
      },
      {
        nombre: "La Cigüeña",
        rol: "Aliado",
        aliados: ["Dumbo", "Timoteo", "Sr. Ratón", "Sra. Jumbo"],
        enemigos: ["Elefantes crueles"],
        descripcion: ["Portadora de bebés", "Cuidadora"],
      },
      {
        nombre: "Sr. Ratón",
        rol: "Aliado",
        aliados: ["Dumbo", "Timoteo", "La Cigüeña", "Sra. Jumbo"],
        enemigos: ["Elefantes crueles"],
        descripcion: ["Empresario", "Ayuda a Dumbo"],
      },
      {
        nombre: "Sra. Jumbo",
        rol: "Aliado",
        aliados: ["Dumbo", "Timoteo", "La Cigüeña", "Sr. Ratón"],
        enemigos: ["Elefantes crueles"],
        descripcion: ["Madre amorosa", "Protectora"],
      },
      {
        nombre: "Elefantes crueles",
        rol: "Villano",
        aliados: [],
        enemigos: ["Dumbo", "Timoteo", "La Cigüeña", "Sr. Ratón", "Sra. Jumbo"],
        descripcion: ["Burlas", "Crueldad"],
      },
      {
        nombre: "Bambi",
        rol: "Protagonista",
        aliados: ["Tambor", "Flor", "Amigo búho"],
        enemigos: ["Hombre"],
        descripcion: ["Ágil", "Velocidad"],
      },
      {
        nombre: "Tambor",
        rol: "Aliado",
        aliados: ["Bambi", "Flor", "Amigo búho"],
        enemigos: ["Hombre"],
        descripcion: ["Buen sentido del humor", "Rapidez"],
      },
      {
        nombre: "Flor",
        rol: "Aliado",
        aliados: ["Bambi", "Tambor", "Amigo búho"],
        enemigos: ["Hombre"],
        descripcion: ["Preocupado por las flores", "Agilidad"],
      },
      {
        nombre: "Amigo búho",
        rol: "Aliado",
        aliados: ["Bambi", "Tambor", "Flor"],
        enemigos: ["Hombre"],
        descripcion: ["Sabiduría", "Consejero"],
      },
      {
        nombre: "Hombre",
        rol: "Villano",
        aliados: [],
        enemigos: ["Bambi", "Tambor", "Flor", "Amigo búho"],
        descripcion: ["Caza", "Amenaza"],
      },
      {
    nombre: "Ariel",
    rol: "Protagonista",
    aliados: ["Flounder", "Sebastián", "Rey Tritón", "Eric"],
    enemigos: ["Úrsula", "Flotsam y Jetsam"],
    descripcion: ["Canto", "Natación"],
  },
  {
    nombre: "Flounder",
    rol: "Aliado",
    aliados: ["Ariel", "Sebastián", "Rey Tritón", "Eric"],
    enemigos: ["Úrsula", "Flotsam y Jetsam"],
    descripcion: ["Amistoso", "Natación"],
  },
  {
    nombre: "Sebastián",
    rol: "Aliado",
    aliados: ["Ariel", "Flounder", "Rey Tritón", "Scuttle"],
    enemigos: ["Úrsula", "Flotsam y Jetsam"],
    descripcion: ["Música", "Consejero"],
  },
  {
    nombre: "Rey Tritón",
    rol: "Aliado",
    aliados: ["Ariel", "Flounder", "Sebastián", "Scuttle"],
    enemigos: ["Úrsula", "Flotsam y Jetsam"],
    descripcion: ["Rey del mar", "Poder tridente"],
  },
  {
    nombre: "Eric",
    rol: "Aliado",
    aliados: ["Ariel"],
    enemigos: ["Úrsula", "Flotsam y Jetsam"],
    descripcion: ["Príncipe", "Valiente"],
  },
  {
    nombre: "Úrsula",
    rol: "Villano",
    aliados: ["Flotsam y Jetsam"],
    enemigos: ["Ariel", "Rey Tritón", "Sebastián"],
    descripcion: ["Magia negra", "Transformación"],
  },
  {
    nombre: "Scuttle",
    rol: "Aliado",
    aliados: ["Ariel", "Sebastián"],
    enemigos: ["Úrsula", "Flotsam y Jetsam"],
    descripcion: ["Amigo de Ariel", "Conocimiento del mundo humano"],
  },
  {
    nombre: "Flotsam y Jetsam",
    rol: "Villanos",
    aliados: ["Úrsula"],
    enemigos: ["Ariel", "Rey Tritón", "Sebastián"],
    descripcion: ["Espionaje", "Sigilosos"],
  },
  {
    nombre: "Peter Pan",
    rol: "Protagonista",
    aliados: ["Campanita", "Wendy", "John", "Michael"],
    enemigos: ["Capitán Garfio", "Smee"],
    descripcion: ["Vuelo", "Habilidad con la espada", "Nunca Jamás"],
  },
  {
    nombre: "Campanita",
    rol: "Aliado",
    aliados: ["Peter Pan", "Wendy", "John", "Michael"],
    enemigos: ["Capitán Garfio"],
    descripcion: ["Vuelo", "Magia", "Protectora de Peter Pan"],
  },
  {
    nombre: "Capitán Garfio",
    rol: "Villano",
    aliados: ["Smee", "Piratas"],
    enemigos: ["Peter Pan", "Campanita"],
    descripcion: ["Espadachín", "Astucia", "Obsesión por vengarse de Peter Pan"],
  },
  {
    nombre: "Wendy",
    rol: "Aliado",
    aliados: ["Peter Pan", "Campanita", "John", "Michael"],
    enemigos: ["Capitán Garfio"],
    descripcion: ["Imaginación", "Liderazgo", "Aventurera"],
  },
  {
    nombre: "John",
    rol: "Aliado",
    aliados: ["Peter Pan", "Campanita", "Wendy", "Michael"],
    enemigos: ["Capitán Garfio"],
    descripcion: ["Curiosidad", "Intelecto", "Hermano leal"],
  },
  {
    nombre: "Michael",
    rol: "Aliado",
    aliados: ["Peter Pan", "Campanita", "Wendy", "John"],
    enemigos: ["Capitán Garfio"],
    descripcion: ["Inocencia", "Alegría", "Hermano más joven"],
  },
  {
    nombre: "Cocodrilo",
    rol: "Neutro",
    aliados: ["Peter Pan"],
    enemigos: ["Capitán Garfio"],
    descripcion: ["Devorador de relojes", "Persecución constante"],
  },
  {
    nombre: "Tigrilla",
    rol: "Aliado",
    aliados: ["Peter Pan", "Campanita"],
    enemigos: ["Capitán Garfio", "Piratas"],
    descripcion: ["Habilidad felina", "Agilidad", "Valentía"],
  },
  {
    nombre: "La Dama",
    rol: "Protagonista",
    aliados: ["El Vagabundo", "Jim Querido", "Darling"],
    enemigos: ["Si", "Am"],
    descripcion: ["Elegancia", "Buena educación"],
  },
  {
    nombre: "El Vagabundo",
    rol: "Protagonista",
    aliados: ["La Dama", "Jim Querido", "Darling"],
    enemigos: ["Si", "Am"],
    descripcion: ["Astucia", "Libertad", "Conocedor de la calle"],
  },
  {
    nombre: "Si y Am",
    rol: "Villanos",
    aliados: [],
    enemigos: ["La Dama", "El Vagabundo", "Jim Querido", "Darling"],
    descripcion: ["Travesuras", "Manipulación"],
  },
  {
    nombre: "Jim Querido",
    rol: "Aliado",
    aliados: ["La Dama", "El Vagabundo", "Darling"],
    enemigos: ["Si", "Am"],
    descripcion: ["Amor familiar", "Comprensión"],
  },
  {
    nombre: "Darling",
    rol: "Aliado",
    aliados: ["La Dama", "El Vagabundo", "Jim Querido"],
    enemigos: ["Si", "Am"],
    descripcion: ["Cariño", "Cuidado"],
  },
  {
    nombre: "Pongo",
    rol: "Protagonista",
    aliados: ["Perdita", "Roger", "Anita"],
    enemigos: ["Cruella de Vil"],
    descripcion: ["Astucia", "Lealtad", "Perseverancia"],
  },
  {
    nombre: "Perdita",
    rol: "Protagonista",
    aliados: ["Pongo", "Roger", "Anita"],
    enemigos: ["Cruella de Vil"],
    descripcion: ["Maternidad", "Lealtad", "Agilidad"],
  },
  {
    nombre: "Roger",
    rol: "Aliado",
    aliados: ["Pongo", "Perdita", "Anita"],
    enemigos: ["Cruella de Vil"],
    descripcion: ["Música", "Creatividad"],
  },
  {
    nombre: "Anita",
    rol: "Aliado",
    aliados: ["Pongo", "Perdita", "Roger"],
    enemigos: ["Cruella de Vil"],
    descripcion: ["Diseño de moda", "Amor por los animales"],
  },
  {
    nombre: "Cruella de Vil",
    rol: "Villana",
    aliados: ["Jasper", "Horace"],
    enemigos: ["Pongo", "Perdita", "Roger", "Anita"],
    descripcion: ["Obsesión por la piel de dálmata", "Crueldad"],
  },
  {
    nombre: "Aurora",
    rol: "Protagonista",
    aliados: ["Príncipe Felipe", "Hadas madrinas"],
    enemigos: ["Maléfica"],
    descripcion: ["Gracia", "Canto", "Bondad"],
  },
  {
    nombre: "Príncipe Felipe",
    rol: "Aliado",
    aliados: ["Aurora", "Hadas madrinas"],
    enemigos: ["Maléfica"],
    descripcion: ["Valentía", "Espada habilidosa"],
  },
  {
    nombre: "Maléfica",
    rol: "Villana",
    aliados: ["Ravenna"],
    enemigos: ["Aurora", "Príncipe Felipe", "Hadas madrinas"],
    descripcion: ["Magia oscura", "Transformación en dragón"],
  },
  {
    nombre: "Hadas madrinas",
    rol: "Aliado",
    aliados: ["Aurora", "Príncipe Felipe"],
    enemigos: ["Maléfica"],
    descripcion: ["Magia benevolente", "Protección"],
  },
  {
    nombre: "Cenicienta", //Cenicienta 2015 
    actriz: "Lily James",
    rol: "Protagonista",
    aliados: ["Hada Madrina", "Ratón Jaq", "Ratón Gus"],
    enemigos: ["Madrastra", "Hermanastra Anastasia", "Hermanastra Drizella"],
    descripcion: ["Bondad", "Resiliencia", "Gentileza"],
  },
  {
    nombre: "Príncipe Kit",
    actor: "Richard Madden",
    rol: "Aliado",
    aliados: ["Cenicienta", "Rey"],
    enemigos: ["Madrastra"],
    descripcion: ["Valentía", "Compasión"],
  },
  {
    nombre: "Madrastra",
    actriz: "Cate Blanchett",
    rol: "Villana",
    aliados: ["Hermanastra Anastasia", "Hermanastra Drizella"],
    enemigos: ["Cenicienta"],
    descripcion: ["Astucia", "Envidia"],
  },
  {
    nombre: "Hermanastra Anastasia",
    actriz: "Holliday Grainger",
    rol: "Villana",
    aliados: ["Madrastra", "Hermanastra Drizella"],
    enemigos: ["Cenicienta"],
    descripcion: ["Arrogancia", "Celos"],
  },
  {
    nombre: "Hermanastra Drizella",
    actriz: "Sophie McShera",
    rol: "Villana",
    aliados: ["Madrastra", "Hermanastra Anastasia"],
    enemigos: ["Cenicienta"],
    descripcion: ["Arrogancia", "Celos"],
  },
  {
    nombre: "Rey",
    actor: "Derek Jacobi",
    rol: "Aliado",
    aliados: ["Príncipe Kit", "Cenicienta"],
    enemigos: ["Madrastra"],
    descripcion: ["Sabiduría", "Amor paternal"],
  },
  {
    nombre: "Hada Madrina",
    actriz: "Helena Bonham Carter",
    rol: "Aliado",
    aliados: ["Cenicienta"],
    enemigos: ["Madrastra"],
    descripcion: ["Magia", "Generosidad"],
  },
  {
    nombre: "Ratón Jaq",
    actor: "Rob Brydon",
    rol: "Aliado",
    aliados: ["Cenicienta", "Ratón Gus"],
    enemigos: ["Madrastra", "Hermanastra Anastasia", "Hermanastra Drizella"],
    descripcion: ["Astucia", "Lealtad"],
  },
  {
    nombre: "Ratón Gus",
    actor: "James Corden",
    rol: "Aliado",
    aliados: ["Cenicienta", "Ratón Jaq"],
    enemigos: ["Madrastra", "Hermanastra Anastasia", "Hermanastra Drizella"],
    descripcion: ["Valentía", "Dulzura"],
  },
  {
    nombre: "Mowgli",
    rol: "Protagonista",
    aliados: ["Baloo", "Bagheera", "Hathi Jr.", "Rey Louie"],
    enemigos: ["Shere Khan", "Kaa"],
    descripcion: ["Supervivencia en la selva", "Amistad con animales"],
  },
  {
    nombre: "Baloo",
    rol: "Aliado",
    aliados: ["Mowgli", "Bagheera", "Hathi Jr.", "Rey Louie"],
    enemigos: ["Shere Khan"],
    descripcion: ["Sabiduría", "Habilidad para cantar"],
  },
  {
    nombre: "Bagheera",
    rol: "Aliado",
    aliados: ["Mowgli", "Baloo", "Hathi Jr.", "Rey Louie"],
    enemigos: ["Shere Khan"],
    descripcion: ["Agilidad", "Intelecto"],
  },
  {
    nombre: "Shere Khan",
    rol: "Villano",
    aliados: ["Kaa"],
    enemigos: ["Mowgli", "Baloo", "Bagheera"],
    descripcion: ["Fuerza", "Astucia"],
  },
  {
    nombre: "Kaa",
    rol: "Villana",
    aliados: ["Shere Khan"],
    enemigos: ["Mowgli", "Baloo", "Bagheera"],
    descripcion: ["Hipnotismo", "Sigilosa"],
  },
  {
    nombre: "Rey Louie",
    rol: "Aliado",
    aliados: ["Mowgli", "Baloo", "Bagheera"],
    enemigos: ["Shere Khan"],
    descripcion: ["Inteligencia", "Deseo de ser humano"],
  },
  {
    nombre: "Aladdín",
    rol: "Protagonista",
    aliados: ["Jazmín", "Genio", "Abu", "Sultán", "Rajah"],
    enemigos: ["Jafar", "Iago"],
    descripcion: ["Agilidad", "Astucia", "Deseos del Genio"],
  },
  {
    nombre: "Jazmín",
    rol: "Aliada",
    aliados: ["Aladdín", "Genio", "Abu", "Sultán", "Rajah"],
    enemigos: ["Jafar", "Iago"],
    descripcion: ["Inteligencia", "Valentía"],
  },
  {
    nombre: "Genio",
    rol: "Aliado",
    aliados: ["Aladdín", "Jazmín", "Abu", "Sultán", "Rajah"],
    enemigos: ["Jafar", "Iago"],
    descripcion: ["Concesión de deseos", "Humor"],
  },
  {
    nombre: "Jafar",
    rol: "Villano",
    aliados: ["Iago"],
    enemigos: ["Aladdín", "Jazmín", "Genio"],
    descripcion: ["Magia oscura", "Ambición"],
  },
  {
    nombre: "Iago",
    rol: "Villano",
    aliados: ["Jafar"],
    enemigos: ["Aladdín", "Jazmín", "Genio"],
    descripcion: ["Astucia", "Habla"],
  },
  {
    nombre: "Sultán",
    rol: "Aliado",
    aliados: ["Jazmín", "Aladdín", "Genio", "Rajah"],
    enemigos: ["Jafar", "Iago"],
    descripcion: ["Gobernar Agrabah", "Benevolencia"],
  },
  {
    nombre: "Rajah",
    rol: "Aliado",
    aliados: ["Jazmín", "Aladdín", "Genio", "Sultán"],
    enemigos: ["Jafar", "Iago"],
    descripcion: ["Protección de Jazmín", "Fuerza felina"],
  },
  {
    nombre: "Mulan",
    rol: "Protagonista",
    aliados: ["Mushu", "Li Shang", "Cri-Kee", "Yao", "Ling", "Chien-Po"],
    enemigos: ["Shan Yu", "Hun"],
    descripcion: ["Valor", "Habilidad en combate"],
  },
  {
    nombre: "Mushu",
    rol: "Aliado",
    aliados: ["Mulan", "Li Shang", "Cri-Kee", "Yao", "Ling", "Chien-Po"],
    enemigos: ["Shan Yu", "Hun"],
    descripcion: ["Dragón guardian", "Hablador"],
  },
  {
    nombre: "Li Shang",
    rol: "Aliado",
    aliados: ["Mulan", "Mushu", "Cri-Kee", "Yao", "Ling", "Chien-Po"],
    enemigos: ["Shan Yu", "Hun"],
    descripcion: ["Liderazgo", "Habilidad en combate"],
  },
  {
    nombre: "Shan Yu",
    rol: "Villano",
    aliados: ["Hun"],
    enemigos: ["Mulan", "Mushu", "Li Shang", "Yao", "Ling", "Chien-Po"],
    descripcion: ["Fuerza", "Estrategia militar"],
  },
  {
    nombre: "Cri-Kee",
    rol: "Aliado",
    aliados: ["Mulan", "Mushu", "Li Shang", "Yao", "Ling", "Chien-Po"],
    enemigos: ["Shan Yu", "Hun"],
    descripcion: ["Buena suerte", "Compañero leal"],
  },
  {
    nombre: "Yao",
    rol: "Aliado",
    aliados: ["Mulan", "Mushu", "Li Shang", "Cri-Kee", "Ling", "Chien-Po"],
    enemigos: ["Shan Yu", "Hun"],
    descripcion: ["Fuerza", "Valentía"],
  },
  {
    nombre: "Ling",
    rol: "Aliado",
    aliados: ["Mulan", "Mushu", "Li Shang", "Cri-Kee", "Yao", "Chien-Po"],
    enemigos: ["Shan Yu", "Hun"],
    descripcion: ["Agilidad", "Humor"],
  },
  {
    nombre: "Chien-Po",
    rol: "Aliado",
    aliados: ["Mulan", "Mushu", "Li Shang", "Cri-Kee", "Yao", "Ling"],
    enemigos: ["Shan Yu", "Hun"],
    descripcion: ["Fuerza", "Amabilidad"],
  },
  {
    nombre: "Emperador",
    rol: "Aliado",
    aliados: ["Mulan", "Mushu", "Li Shang"],
    enemigos: ["Shan Yu", "Hun"],
    descripcion: ["Liderazgo", "Sabiduría"],
  },
  {
    nombre: "Hércules",
    rol: "Protagonista",
    aliados: ["Phil", "Meg", "Pegaso", "Zeus"],
    enemigos: ["Hades", "Pain", "Panic"],
    descripcion: ["Fuerza sobrehumana", "Habilidad en combate"],
  },
  {
    nombre: "Phil",
    rol: "Aliado",
    aliados: ["Hércules", "Meg", "Pegaso", "Zeus"],
    enemigos: ["Hades", "Pain", "Panic"],
    descripcion: ["Entrenador de héroes", "Sabiduría"],
  },
  {
    nombre: "Meg",
    rol: "Aliada",
    aliados: ["Hércules", "Phil", "Pegaso", "Zeus"],
    enemigos: ["Hades", "Pain", "Panic"],
    descripcion: ["Inteligencia", "Amor por Hércules"],
  },
  {
    nombre: "Hades",
    rol: "Villano",
    aliados: ["Pain", "Panic"],
    enemigos: ["Hércules", "Meg", "Phil", "Zeus"],
    descripcion: ["Magia oscura", "Astucia"],
  },
  {
    nombre: "Pain",
    rol: "Villano",
    aliados: ["Hades", "Panic"],
    enemigos: ["Hércules", "Meg", "Phil", "Zeus"],
    descripcion: ["Travesuras", "Lealtad a Hades"],
  },
  {
    nombre: "Panic",
    rol: "Villano",
    aliados: ["Hades", "Pain"],
    enemigos: ["Hércules", "Meg", "Phil", "Zeus"],
    descripcion: ["Travesuras", "Lealtad a Hades"],
  },
  {
    nombre: "Zeus",
    rol: "Aliado",
    aliados: ["Hércules", "Phil", "Meg", "Pegaso"],
    enemigos: ["Hades", "Pain", "Panic"],
    descripcion: ["Poder divino", "Amor paternal"],
  },
  {
    nombre: "Pegaso",
    rol: "Aliado",
    aliados: ["Hércules", "Zeus"],
    enemigos: ["Hades"],
    descripcion: ["Vuelo", "Lealtad"],
  },
  {
    nombre: "Tarzán",
    rol: "Protagonista",
    aliados: ["Jane Porter", "Profesor Archimedes Q. Porter", "Tantor", "Terk"],
    enemigos: ["Clayton", "Sabor"],
    descripcion: ["Agilidad", "Comunicación con animales"],
  },
  {
    nombre: "Jane Porter",
    rol: "Aliada",
    aliados: ["Tarzán", "Profesor Archimedes Q. Porter", "Tantor", "Terk"],
    enemigos: ["Clayton", "Sabor"],
    descripcion: ["Exploradora", "Amor por Tarzán"],
  },
  {
    nombre: "Profesor Archimedes Q. Porter",
    rol: "Aliado",
    aliados: ["Tarzán", "Jane Porter", "Tantor", "Terk"],
    enemigos: ["Clayton", "Sabor"],
    descripcion: ["Científico", "Curiosidad"],
  },
  {
    nombre: "Tantor",
    rol: "Aliado",
    aliados: ["Tarzán", "Jane Porter", "Profesor Archimedes Q. Porter", "Terk"],
    enemigos: ["Clayton", "Sabor"],
    descripcion: ["Miedo exagerado", "Fuerza"],
  },
  {
    nombre: "Terk",
    rol: "Aliado",
    aliados: ["Tarzán", "Jane Porter", "Profesor Archimedes Q. Porter", "Tantor"],
    enemigos: ["Clayton", "Sabor"],
    descripcion: ["Mono travieso", "Agilidad"],
  },
  {
    nombre: "Clayton",
    rol: "Villano",
    aliados: [],
    enemigos: ["Tarzán", "Jane Porter", "Profesor Archimedes Q. Porter", "Tantor", "Terk"],
    descripcion: ["Caza", "Ambición"],
  },
  {
    nombre: "Sabor", //el leopardo
    rol: "Villano",
    aliados: [],
    enemigos: ["Tarzán", "Jane Porter", "Profesor Archimedes Q. Porter", "Tantor", "Terk"],
    descripcion: ["Fuerza", "Agresividad"],
  },
  {
    nombre: "Elsa",
    rol: "Protagonista",
    aliados: ["Anna", "Olaf", "Kristoff", "Sven"],
    enemigos: ["Hans"],
    descripcion: ["Poderes de hielo", "Control de nieve"],
  },
  {
    nombre: "Anna",
    rol: "Aliada",
    aliados: ["Elsa", "Olaf", "Kristoff", "Sven"],
    enemigos: ["Hans"],
    descripcion: ["Valentía", "Amor fraternal"],
  },
  {
    nombre: "Olaf",
    rol: "Aliado",
    aliados: ["Elsa", "Anna", "Kristoff", "Sven"],
    enemigos: ["Hans"],
    descripcion: ["Muñeco de nieve animado", "Inocencia"],
  },
  {
    nombre: "Kristoff",
    rol: "Aliado",
    aliados: ["Elsa", "Anna", "Olaf", "Sven"],
    enemigos: ["Hans"],
    descripcion: ["Montañero", "Lealtad"],
  },
  {
    nombre: "Sven",
    rol: "Aliado",
    aliados: ["Elsa", "Anna", "Olaf", "Kristoff"],
    enemigos: ["Hans"],
    descripcion: ["Reno compañero", "Fuerza"],
  },
  {
    nombre: "Hans",
    rol: "Villano",
    aliados: [],
    enemigos: ["Elsa", "Anna", "Olaf", "Kristoff", "Sven"],
    descripcion: ["Engaño", "Ambición"],
  },
  {
    nombre: "Rapunzel",
    rol: "Protagonista",
    aliados: ["Flynn Rider", "Pascal", "Maximus"],
    enemigos: ["Madre Gothel"],
    descripcion: ["Cabello mágico", "Ingenio"],
  },
  {
    nombre: "Flynn Rider",
    rol: "Aliado",
    aliados: ["Rapunzel", "Pascal", "Maximus"],
    enemigos: ["Madre Gothel"],
    descripcion: ["Ladrón transformado", "Carisma"],
  },
  {
    nombre: "Pascal",
    rol: "Aliado",
    aliados: ["Rapunzel", "Flynn Rider", "Maximus"],
    enemigos: ["Madre Gothel"],
    descripcion: ["Camaleón compañero", "Astucia"],
  },
  {
    nombre: "Maximus",
    rol: "Aliado",
    aliados: ["Rapunzel", "Flynn Rider", "Pascal"],
    enemigos: ["Madre Gothel"],
    descripcion: ["Caballo leal", "Habilidad en combate"],
  },
  {
    nombre: "Madre Gothel",
    rol: "Villana",
    aliados: [],
    enemigos: ["Rapunzel", "Flynn Rider", "Pascal", "Maximus"],
    descripcion: ["Inmortalidad temporal", "Manipulación"],
  },
  {
    nombre: "Mary Poppins",
    actriz: "Julie Andrews",
    rol: "Protagonista",
    aliados: ["Bert", "Jane Banks", "Michael Banks", "Sr. Banks", "Sra. Banks"],
    enemigos: ["Sr. Dawes Sr.", "Sr. Dawes Jr."],
    descripcion: ["Niñera mágica", "Canto encantador"],
  },
  {
    nombre: "Bert",
    actor: "Dick Van Dyke",
    rol: "Aliado",
    aliados: ["Mary Poppins", "Jane Banks", "Michael Banks", "Sr. Banks", "Sra. Banks"],
    enemigos: ["Sr. Dawes Sr.", "Sr. Dawes Jr."],
    descripcion: ["Chim Chim Cher-ee", "Hombre del tiempo"],
  },
  {
    nombre: "Jane Banks",
    actriz: "Karen Dotrice",
    rol: "Aliada",
    aliados: ["Mary Poppins", "Bert", "Michael Banks", "Sr. Banks", "Sra. Banks"],
    enemigos: ["Sr. Dawes Sr.", "Sr. Dawes Jr."],
    descripcion: ["Travesuras infantiles", "Curiosidad"],
  },
  {
    nombre: "Michael Banks",
    actor: "Matthew Garber",
    rol: "Aliado",
    aliados: ["Mary Poppins", "Bert", "Jane Banks", "Sr. Banks", "Sra. Banks"],
    enemigos: ["Sr. Dawes Sr.", "Sr. Dawes Jr."],
    descripcion: ["Travesuras infantiles", "Imaginación"],
  },
  {
    nombre: "Sr. Banks",
    actor: "David Tomlinson",
    rol: "Aliado",
    aliados: ["Mary Poppins", "Bert", "Jane Banks", "Michael Banks", "Sra. Banks"],
    enemigos: ["Sr. Dawes Sr.", "Sr. Dawes Jr."],
    descripcion: ["Banquero", "Aprendizaje familiar"],
  },
  {
    nombre: "Sra. Banks",
    actriz: "Glynis Johns",
    rol: "Aliada",
    aliados: ["Mary Poppins", "Bert", "Jane Banks", "Michael Banks", "Sr. Banks"],
    enemigos: ["Sr. Dawes Sr.", "Sr. Dawes Jr."],
    descripcion: ["Sufragista", "Amor maternal"],
  },
  {
    nombre: "Sr. Dawes Sr.",
    actor: "Arthur Malet",
    rol: "Villano",
    aliados: [],
    enemigos: ["Mary Poppins", "Bert", "Jane Banks", "Michael Banks", "Sr. Banks", "Sra. Banks"],
    descripcion: ["Banquero codicioso", "Actuario exigente"],
  },
  {
    nombre: "Sr. Dawes Jr.",
    actor: "Dick Van Dyke",
    rol: "Villano",
    aliados: [],
    enemigos: ["Mary Poppins", "Bert", "Jane Banks", "Michael Banks", "Sr. Banks", "Sra. Banks"],
    descripcion: ["Banquero codicioso", "Actuario exigente"],
  },
  {
    nombre: "Vaiana",
    rol: "Protagonista",
    aliados: ["Maui", "Gramma Tala"],
    enemigos: ["Te Ka"],
    descripcion: ["Navegación", "Conexión con el océano"],
  },
  {
    nombre: "Maui",
    rol: "Aliado",
    aliados: ["Vaiana", "Gramma Tala"],
    enemigos: ["Te Ka"],
    descripcion: ["Formación de islas", "Poderes mágicos"],
  },
  {
    nombre: "Gramma Tala",
    rol: "Aliada",
    aliados: ["Vaiana", "Maui"],
    enemigos: ["Te Ka"],
    descripcion: ["Historias y leyendas", "Consejos sabios"],
  },
  {
    nombre: "Te Ka",
    rol: "Villano",
    aliados: [],
    enemigos: ["Vaiana", "Maui", "Gramma Tala"],
    descripcion: ["Furia volcánica", "Transformación"],
  },
  {
    nombre: "Judy Hopps",
    rol: "Protagonista",
    aliados: ["Nick Wilde", "Chief Bogo", "Flash", "Yax"],
    enemigos: ["Bellwether"],
    descripcion: ["Oficial de policía", "Ingenio"],
  },
  {
    nombre: "Nick Wilde",
    rol: "Aliado",
    aliados: ["Judy Hopps", "Chief Bogo", "Flash", "Yax"],
    enemigos: ["Bellwether"],
    descripcion: ["Estafador", "Astucia"],
  },
  {
    nombre: "Chief Bogo",
    rol: "Aliado",
    aliados: ["Judy Hopps", "Nick Wilde", "Flash", "Yax"],
    enemigos: ["Bellwether"],
    descripcion: ["Jefe de policía", "Liderazgo"],
  },
  {
    nombre: "Flash",
    rol: "Aliado",
    aliados: ["Judy Hopps", "Nick Wilde", "Chief Bogo", "Yax"],
    enemigos: ["Bellwether"],
    descripcion: ["Perezoso", "Experto en multas"],
  },
  {
    nombre: "Yax",
    rol: "Aliado",
    aliados: ["Judy Hopps", "Nick Wilde", "Chief Bogo", "Flash"],
    enemigos: ["Bellwether"],
    descripcion: ["Hippie", "Conexión con la naturaleza"],
  },
  {
    nombre: "Bellwether",
    rol: "Villana",
    aliados: [],
    enemigos: ["Judy Hopps", "Nick Wilde", "Chief Bogo", "Flash", "Yax"],
    descripcion: ["Complot", "Manipulación"],
  },
  {
    nombre: "Quasimodo",
    rol: "Protagonista",
    aliados: ["Esmeralda", "Capitán Febo", "Gárgolas"],
    enemigos: ["Claude Frollo"],
    descripcion: ["Campanero de Notre Dame", "Agilidad"],
  },
  {
    nombre: "Esmeralda",
    rol: "Aliada",
    aliados: ["Quasimodo", "Capitán Febo", "Gárgolas"],
    enemigos: ["Claude Frollo"],
    descripcion: ["Bailarina", "Valentía"],
  },
  {
    nombre: "Capitán Febo",
    rol: "Aliado",
    aliados: ["Quasimodo", "Esmeralda", "Gárgolas"],
    enemigos: ["Claude Frollo"],
    descripcion: ["Capitán de la guardia", "Justicia"],
  },
  {
    nombre: "Gárgolas",
    rol: "Aliados",
    aliados: ["Quasimodo", "Esmeralda", "Capitán Febo"],
    enemigos: ["Claude Frollo"],
    descripcion: ["Vigilancia", "Lealtad"],
  },
  {
    nombre: "Claude Frollo",
    rol: "Villano",
    aliados: [],
    enemigos: ["Quasimodo", "Esmeralda", "Capitán Febo", "Gárgolas"],
    descripcion: ["Fanatismo religioso", "Crueldad"],
  },
  {
    nombre: "Jim Hawkins",
    rol: "Protagonista",
    aliados: ["John Silver", "Dr. Doppler", "Capitán Amelia", "B.E.N.", "Mr. Arrow"],
    enemigos: ["Scroop"],
    descripcion: ["Aventurero", "Determinación"],
  },
  {
    nombre: "John Silver",
    rol: "Aliado",
    aliados: ["Jim Hawkins", "Dr. Doppler", "Capitán Amelia", "B.E.N.", "Mr. Arrow"],
    enemigos: ["Scroop"],
    descripcion: ["Pirata cocinero", "Corazón noble"],
  },
  {
    nombre: "Dr. Doppler",
    rol: "Aliado",
    aliados: ["Jim Hawkins", "John Silver", "Capitán Amelia", "B.E.N.", "Mr. Arrow"],
    enemigos: ["Scroop"],
    descripcion: ["Científico", "Valentía"],
  },
  {
    nombre: "Capitán Amelia",
    rol: "Aliada",
    aliados: ["Jim Hawkins", "John Silver", "Dr. Doppler", "B.E.N.", "Mr. Arrow"],
    enemigos: ["Scroop"],
    descripcion: ["Capitán del RLS Legacy", "Habilidad en combate"],
  },
  {
    nombre: "B.E.N.",
    rol: "Aliado",
    aliados: ["Jim Hawkins", "John Silver", "Dr. Doppler", "Capitán Amelia", "Mr. Arrow"],
    enemigos: ["Scroop"],
    descripcion: ["Androide amistoso", "Conocimiento del Tesoro"],
  },
  {
    nombre: "Scroop",
    rol: "Villano",
    aliados: [],
    enemigos: ["Jim Hawkins", "John Silver", "Dr. Doppler", "Capitán Amelia", "B.E.N.", "Mr. Arrow"],
    descripcion: ["Pirata cyborg", "Agresividad"],
  },
  {
    nombre: "Milo Thatch",
    rol: "Protagonista",
    aliados: ["Kida", "Comandante Rourke", "Audrey", "Vincenzo Santorini"],
    enemigos: ["Lyle Tiberius Rourke", "Helga Sinclair"],
    descripcion: ["Lingüista", "Arqueólogo"],
  },
  {
    nombre: "Kida",
    rol: "Aliada",
    aliados: ["Milo Thatch", "Comandante Rourke", "Audrey", "Vincenzo Santorini"],
    enemigos: ["Lyle Tiberius Rourke", "Helga Sinclair"],
    descripcion: ["Princesa de Atlantis", "Conexión con cristales"],
  },
  {
    nombre: "Comandante Rourke",
    rol: "Aliado",
    aliados: ["Milo Thatch", "Kida", "Audrey", "Vincenzo Santorini"],
    enemigos: ["Lyle Tiberius Rourke", "Helga Sinclair"],
    descripcion: ["Líder de la expedición", "Ambición sin escrúpulos"],
  },
  {
    nombre: "Audrey",
    rol: "Aliada",
    aliados: ["Milo Thatch", "Kida", "Comandante Rourke", "Vincenzo Santorini"],
    enemigos: ["Lyle Tiberius Rourke", "Helga Sinclair"],
    descripcion: ["Mecánica", "Lealtad"],
  },
  {
    nombre: "Vincenzo Santorini",
    rol: "Aliado",
    aliados: ["Milo Thatch", "Kida", "Comandante Rourke", "Audrey"],
    enemigos: ["Lyle Tiberius Rourke", "Helga Sinclair"],
    descripcion: ["Excavador", "Pasión por la historia"],
  },
  {
    nombre: "Lyle Tiberius Rourke",
    rol: "Villano",
    aliados: [],
    enemigos: ["Milo Thatch", "Kida", "Comandante Rourke", "Audrey", "Vincenzo Santorini"],
    descripcion: ["Traición", "Ambición desmedida"],
  },
  {
    nombre: "Helga Sinclair",
    rol: "Villana",
    aliados: [],
    enemigos: ["Milo Thatch", "Kida", "Comandante Rourke", "Audrey", "Vincenzo Santorini"],
    descripcion: ["Mercenaria", "Habilidad en combate"],
  },
  {
    nombre: "Mowgli", //2016
    actor: "Neel Sethi",
    rol: "Protagonista",
    aliados: ["Baloo", "Bagheera", "Raksha", "Rey Louie"],
    enemigos: ["Shere Khan"],
    descripcion: ["Supervivencia en la selva"],
  },
  {
    nombre: "Baloo",
    rol: "Aliado",
    aliados: ["Mowgli", "Bagheera", "Raksha", "Rey Louie"],
    enemigos: ["Shere Khan"],
    descripcion: ["Oso despreocupado"],
  },
  {
    nombre: "Bagheera",
    rol: "Aliado",
    aliados: ["Mowgli", "Baloo", "Raksha", "Rey Louie"],
    enemigos: ["Shere Khan"],
    descripcion: ["Pantera protectora"],
  },
  {
    nombre: "Raksha",
    rol: "Aliada",
    aliados: ["Mowgli", "Baloo", "Bagheera", "Rey Louie"],
    enemigos: ["Shere Khan"],
    descripcion: ["Loba cariñosa"],
  },
  {
    nombre: "Rey Louie",
    rol: "Aliado",
    aliados: ["Mowgli", "Baloo", "Bagheera", "Raksha"],
    enemigos: ["Shere Khan"],
    descripcion: ["Rey de los monos"],
  },
  {
    nombre: "Shere Khan",
    rol: "Villano",
    aliados: [],
    enemigos: ["Mowgli", "Baloo", "Bagheera", "Raksha", "Rey Louie"],
    descripcion: ["Tigre feroz"],
  },
  {
    nombre: "Mary Poppins",
    actriz: "Emily Blunt",
    rol: "Protagonista",
    aliados: ["Jack", "Los Banks", "Ellen", "Los niños Banks", "Topsy Turvy Poppins"],
    enemigos: ["William Weatherall Wilkins"],
    descripcion: ["Niñera mágica"],
  },
  {
    nombre: "Jack",
    actor: "Lin-Manuel Miranda",
    rol: "Aliado",
    aliados: ["Mary Poppins", "Los Banks", "Ellen", "Los niños Banks", "Topsy Turvy Poppins"],
    enemigos: ["William Weatherall Wilkins"],
    descripcion: ["Lamparero amigable"],
  },
  {
    nombre: "William Weatherall Wilkins",
    actor: "Colin Firth",
    rol: "Villano",
    aliados: [],
    enemigos: ["Mary Poppins", "Jack", "Los Banks", "Ellen", "Los niños Banks", "Topsy Turvy Poppins"],
    descripcion: ["Banquero codicioso"],
  },
  {
    nombre: "Anabel Banks",
    actriz: "Pixie Davies",
    rol: "Aliada",
    aliados: ["Mary Poppins", "Jack", "Ellen", "Topsy Turvy Poppins"],
    enemigos: ["William Weatherall Wilkins"],
    descripcion: ["Imaginación", "Aventuras"],
  },
  {
    nombre: "John Banks",
    actor: "Nathanael Saleh",
    rol: "Aliado",
    aliados: ["Mary Poppins", "Jack", "Ellen", "Topsy Turvy Poppins"],
    enemigos: ["William Weatherall Wilkins"],
    descripcion: ["Imaginación", "Aventuras"],
  },
  {
    nombre: "Georgie Banks",
    actor: "Joel Dawson",
    rol: "Aliado",
    aliados: ["Mary Poppins", "Jack", "Ellen", "Topsy Turvy Poppins"],
    enemigos: ["William Weatherall Wilkins"],
    descripcion: ["Imaginación", "Aventuras"],
  },
  {
    nombre: "Topsy Turvy Poppins",
    actriz: "Meryl Streep",
    rol: "Aliada",
    aliados: ["Mary Poppins", "Jack", "Los Banks", "Ellen", "Los niños Banks"],
    enemigos: ["William Weatherall Wilkins"],
    descripcion: ["Excéntrica prima de Mary Poppins", "Reparación de cosas rotas"],
  },
  {
    nombre: "Alice", //TODO: meter actores
    actriz: "Mia Wasikowska",
    rol: "Protagonista",
    aliados: ["Sombrerero Loco", "Conejo Blanco", "Gato de Cheshire", "Reina Blanca"],
    enemigos: ["Reina Roja", "Jabberwocky"],
    descripcion: ["Viajera entre mundos"],
  },
  {
    nombre: "Sombrerero Loco",
    actor: "Johnny Depp",
    rol: "Aliado",
    aliados: ["Alice", "Conejo Blanco", "Gato de Cheshire", "Reina Blanca"],
    enemigos: ["Reina Roja", "Jabberwocky"],
    descripcion: ["Té y locura"],
  },
  {
    nombre: "Conejo Blanco",
    rol: "Aliado",
    aliados: ["Alice", "Sombrerero Loco", "Gato de Cheshire", "Reina Blanca"],
    enemigos: ["Reina Roja", "Jabberwocky"],
    descripcion: ["Aventurero apresurado"],
  },
  {
    nombre: "Gato de Cheshire",
    rol: "Aliado",
    aliados: ["Alice", "Sombrerero Loco", "Conejo Blanco", "Reina Blanca"],
    enemigos: ["Reina Roja", "Jabberwocky"],
    descripcion: ["Sonrisa misteriosa"],
  },
  {
    nombre: "Reina Blanca",
    actriz: "Anne Hathaway",
    rol: "Aliada",
    aliados: ["Alice", "Sombrerero Loco", "Conejo Blanco", "Gato de Cheshire"],
    enemigos: ["Reina Roja", "Jabberwocky"],
    descripcion: ["Reina benevolente"],
  },
  {
    nombre: "Reina Roja",
    actriz: "Helena Bonham Carter",
    rol: "Villana",
    aliados: [],
    enemigos: ["Alice", "Sombrerero Loco", "Conejo Blanco", "Gato de Cheshire", "Reina Blanca"],
    descripcion: ["Cabeza grande", "Ira desmedida"],
  },
  {
    nombre: "Dumbo", //2019
    rol: "Protagonista",
    aliados: ["Holt Farrier", "Milly Farrier", "Joe Farrier", "Colette Marchant"],
    enemigos: ["V.A. Vandevere"],
    descripcion: ["Elefante volador"],
  },
  {
    nombre: "Holt Farrier",
    actor: "Colin Farrell",
    rol: "Aliado",
    aliados: ["Dumbo", "Milly Farrier", "Joe Farrier", "Colette Marchant"],
    enemigos: ["V.A. Vandevere"],
    descripcion: ["Ex estrella de circo", "Cuidador de elefantes"],
  },
  {
    nombre: "Milly Farrier",
    actriz: "Nico Parker",
    rol: "Aliada",
    aliados: ["Dumbo", "Holt Farrier", "Joe Farrier", "Colette Marchant"],
    enemigos: ["V.A. Vandevere"],
    descripcion: ["Soñadora", "Cuidadora de elefantes"],
  },
  {
    nombre: "Joe Farrier",
    actor: "Finley Hobbins",
    rol: "Aliado",
    aliados: ["Dumbo", "Holt Farrier", "Milly Farrier", "Colette Marchant"],
    enemigos: ["V.A. Vandevere"],
    descripcion: ["Cuidador de elefantes"],
  },
  {
    nombre: "Colette Marchant",
    actriz: "Eva Green",
    rol: "Aliada",
    aliados: ["Dumbo", "Holt Farrier", "Milly Farrier", "Joe Farrier"],
    enemigos: ["V.A. Vandevere"],
    descripcion: ["Acróbata aérea", "Artista circense"],
  },
  {
    nombre: "V.A. Vandevere",
    actor: "Michael Keaton",
    rol: "Villano",
    aliados: [],
    enemigos: ["Dumbo", "Holt Farrier", "Milly Farrier", "Joe Farrier", "Colette Marchant"],
    descripcion: ["Empresario sin escrúpulos"],
  },
  {
    nombre: "Miguel",
    rol: "Protagonista",
    aliados: ["Héctor", "Dante"],
    enemigos: ["Ernesto de la Cruz"],
    descripcion: ["Música", "Viaje a la Tierra de los Muertos"],
  },
  {
    nombre: "Héctor",
    rol: "Aliado",
    aliados: ["Miguel", "Dante"],
    enemigos: ["Ernesto de la Cruz"],
    descripcion: ["Canto", "Conocimiento de la Tierra de los Muertos"],
  },
  {
    nombre: "Ernesto de la Cruz",
    rol: "Villano",
    aliados: [],
    enemigos: ["Miguel", "Héctor", "Dante"],
    descripcion: ["Canto", "Manipulación"],
  },
  {
    nombre: "Coco",
    rol: "Aliada",
    aliados: ["Miguel", "Héctor", "Dante"],
    enemigos: ["Ernesto de la Cruz"],
    descripcion: ["Sabiduría de la familia Rivera"],
  },
  {
    nombre: "Abuelita Elena",
    rol: "Aliada",
    aliados: ["Miguel", "Héctor", "Dante"],
    enemigos: ["Ernesto de la Cruz"],
    descripcion: ["Protección familiar", "Tradición"],
  },
  {
    nombre: "Dante",
    rol: "Aliado",
    aliados: ["Miguel", "Héctor"],
    enemigos: ["Ernesto de la Cruz"],
    descripcion: ["Guía espiritual", "Transformación"],
  },
  {
    nombre: "Imelda",
    rol: "Aliada",
    aliados: ["Miguel", "Héctor"],
    enemigos: ["Ernesto de la Cruz"],
    descripcion: ["Amor maternal", "Control de la Tierra de los Muertos"],
  },
  {
    nombre: "Elsa",
    rol: "Protagonista",
    aliados: ["Anna", "Olaf", "Kristoff", "Sven"],
    enemigos: ["Elementales del Bosque Encantado"],
    descripcion: ["Control de hielo", "Poderes mágicos"],
  },
  {
    nombre: "Anna",
    rol: "Aliada",
    aliados: ["Elsa", "Olaf", "Kristoff", "Sven"],
    enemigos: ["Elementales del Bosque Encantado"],
    descripcion: ["Determinación", "Coraje"],
  },
  {
    nombre: "Olaf",
    rol: "Aliado",
    aliados: ["Elsa", "Anna", "Kristoff", "Sven"],
    enemigos: ["Elementales del Bosque Encantado"],
    descripcion: ["Humor", "Desarmarse a sí mismo"],
  },
  {
    nombre: "Kristoff",
    rol: "Aliado",
    aliados: ["Anna", "Elsa", "Olaf", "Sven"],
    enemigos: ["Elementales del Bosque Encantado"],
    descripcion: ["Montañismo", "Lealtad a Sven"],
  },
  {
    nombre: "Sven",
    rol: "Aliado",
    aliados: ["Anna", "Elsa", "Olaf", "Kristoff"],
    enemigos: ["Elementales del Bosque Encantado"],
    descripcion: ["Renos y trineos", "Amistad con Kristoff"],
  },
  {
    nombre: "Elementales del Bosque Encantado",
    rol: "Enemigos",
    aliados: [],
    enemigos: ["Elsa", "Anna", "Olaf", "Kristoff", "Sven"],
    descripcion: ["Control de la naturaleza"],
  },
  {
    nombre: "Reina Iduna",
    rol: "Aliada",
    aliados: ["Elsa", "Anna", "Olaf", "Kristoff", "Sven"],
    enemigos: ["Elementales del Bosque Encantado"],
    descripcion: ["Amor maternal", "Conocimiento de la historia"],
  },
  {
    nombre: "Teniente Mattias",
    rol: "Aliado",
    aliados: ["Elsa", "Anna", "Olaf", "Kristoff", "Sven"],
    enemigos: ["Elementales del Bosque Encantado"],
    descripcion: ["Líder militar", "Estrategia"],
  },
  {
    nombre: "Raya",
    rol: "Protagonista",
    aliados: ["Tuk Tuk", "Sisu", "Boun", "Noi", "Tong"],
    enemigos: ["Namaari", "Druun"],
    descripcion: ["Lucha con espada", "Conexión con Sisu"],
  },
  {
    nombre: "Tuk Tuk",
    rol: "Aliado",
    aliados: ["Raya", "Sisu", "Boun", "Noi", "Tong"],
    enemigos: ["Namaari", "Druun"],
    descripcion: ["Velocidad", "Resistencia"],
  },
  {
    nombre: "Sisu",
    rol: "Aliada",
    aliados: ["Raya", "Tuk Tuk", "Boun", "Noi", "Tong"],
    enemigos: ["Namaari", "Druun"],
    descripcion: ["Transformación en dragón", "Magia acuática"],
  },
  {
    nombre: "Namaari",
    rol: "Enemiga",
    aliados: [],
    enemigos: ["Raya", "Tuk Tuk", "Sisu", "Boun", "Noi", "Tong"],
    descripcion: ["Destreza con ballesta", "Habilidad táctica"],
  },
  {
    nombre: "Druun",
    rol: "Enemigo",
    aliados: [],
    enemigos: ["Raya", "Tuk Tuk", "Sisu", "Boun", "Noi", "Tong"],
    descripcion: ["Corrupción y destrucción"],
  },
  {
    nombre: "Boun",
    rol: "Aliado",
    aliados: ["Raya", "Tuk Tuk", "Sisu", "Noi", "Tong"],
    enemigos: ["Namaari", "Druun"],
    descripcion: ["Comerciante astuto", "Habilidades culinarias"],
  },
  {
    nombre: "Noi",
    rol: "Aliada",
    aliados: ["Raya", "Tuk Tuk", "Sisu", "Boun", "Tong"],
    enemigos: ["Namaari", "Druun"],
    descripcion: ["Experta en la calle", "Ágil y rápida"],
  },
  {
    nombre: "Tong",
    rol: "Aliado",
    aliados: ["Raya", "Tuk Tuk", "Sisu", "Boun", "Noi"],
    enemigos: ["Namaari", "Druun"],
    descripcion: ["Fuerte y valiente", "Lucha con bumerán"],
  },
  {
    nombre: "Estella / Cruella de Vil",
    actriz: "Emma Stone",
    rol: "Protagonista",
    aliados: ["Jasper", "Horace"],
    enemigos: ["Baronesa von Hellman"],
    descripcion: ["Moda", "Creatividad"],
  },
  {
    nombre: "Jasper",
    actor: "Joel Fry",
    rol: "Aliado",
    aliados: ["Estella / Cruella de Vil", "Horace"],
    enemigos: ["Baronesa von Hellman"],
    descripcion: ["Astucia", "Trabajo de calle"],
  },
  {
    nombre: "Horace",
    actor: "Paul Walter Hauser",
    rol: "Aliado",
    aliados: ["Estella / Cruella de Vil", "Jasper"],
    enemigos: ["Baronesa von Hellman"],
    descripcion: ["Fuerza física", "Lealtad"],
  },
  {
    nombre: "Baronesa von Hellman",
    actriz: "Emma Thompson",
    rol: "Villana",
    aliados: [],
    enemigos: ["Estella / Cruella de Vil", "Jasper", "Horace"],
    descripcion: ["Moda de alta costura", "Crueldad"],
  },
  {
    nombre: "Artie",
    actor: "John McCrea",
    rol: "Aliado",
    aliados: ["Estella / Cruella de Vil"],
    enemigos: ["Baronesa von Hellman"],
    descripcion: ["Diseño de moda alternativa", "Libertad creativa"],
  },
  {
    nombre: "Anita Darling",
    actriz: "Kirby Howell-Baptiste",
    rol: "Aliada",
    aliados: ["Estella / Cruella de Vil"],
    enemigos: ["Baronesa von Hellman"],
    descripcion: ["Periodismo", "Amistad"],
  },
  {
    nombre: "Roger",
    actor: "Kayvan Novak",
    rol: "Aliado",
    aliados: ["Estella / Cruella de Vil"],
    enemigos: ["Baronesa von Hellman"],
    descripcion: ["Músico", "Amor por Anita"],
  },
  {
    nombre: "Luca Paguro",
    rol: "Protagonista",
    aliados: ["Alberto Scorfano", "Giulia Marcovaldo"],
    enemigos: ["Ercole Visconti"],
    descripcion: ["Transformación en monstruo marino", "Curiosidad"],
  },
  {
    nombre: "Alberto Scorfano",
    rol: "Aliado",
    aliados: ["Luca Paguro", "Giulia Marcovaldo"],
    enemigos: ["Ercole Visconti"],
    descripcion: ["Transformación en monstruo marino", "Inventor"],
  },
  {
    nombre: "Giulia Marcovaldo",
    rol: "Aliada",
    aliados: ["Luca Paguro", "Alberto Scorfano"],
    enemigos: ["Ercole Visconti"],
    descripcion: ["Amistad", "Ciclismo"],
  },
  {
    nombre: "Daniela Paguro",
    rol: "Aliada",
    aliados: ["Luca Paguro"],
    enemigos: ["Ercole Visconti"],
    descripcion: ["Preocupación maternal", "Cuidado de criaturas marinas"],
  },
  {
    nombre: "Ercole Visconti",
    rol: "Villano",
    aliados: [],
    enemigos: ["Luca Paguro", "Alberto Scorfano", "Giulia Marcovaldo"],
    descripcion: ["Competitividad", "Intimidación"],
  },
  {
    nombre: "Massimo Marcovaldo",
    rol: "Aliado",
    aliados: ["Giulia Marcovaldo"],
    enemigos: ["Ercole Visconti"],
    descripcion: ["Pescador", "Apoyo a Giulia"],
  }
];
  
  
mongoose
  .connect(MONGODB_URL)
  .then(async () => {
    const allCharacters = await Character.find();
    if (allCharacters.length > 0) {
      await Character.collection.drop();
      console.log("Personajes borrados");
    }
  })
  .catch((error) => console.log("Error borrando los personajes", error))
  .then(async () => {
    const characterMap = characters.map((character) => new Character(character));
    await Character.insertMany(characterMap);
    console.log("Personajes insertados");
  })
  .catch((error) => console.log("Error insertando los personajes", error))
  .finally(() => mongoose.disconnect());